In [ ]:
# Load data
from google.colab import drive
drive.mount('/content/drive')
import numpy as np
import pandas as pd

push_normalized = pd.read_csv('/content/drive/MyDrive/MelodyResearch/final_csv/final_normalized/'+ 'push_normalized.csv')
pull_normalized = pd.read_csv('/content/drive/MyDrive/MelodyResearch/final_csv/final_normalized/'+  'pull_normalized.csv')
folding_normalized = pd.read_csv('/content/drive/MyDrive/MelodyResearch/final_csv/final_normalized/'+  'folding_normalized.csv')
sponge_push_normalized = pd.read_csv('/content/drive/MyDrive/MelodyResearch/final_csv/final_normalized/'+  'sponge_push_normalized.csv')

push_normalized_25 = pd.read_csv('/content/drive/MyDrive/MelodyResearch/final_csv/final_normalized/'+  'push_normalized_light_0.25.csv')
push_normalized_50 = pd.read_csv('/content/drive/MyDrive/MelodyResearch/final_csv/final_normalized/'+  'push_normalized_medium_0.5.csv')
push_normalized_75 = pd.read_csv('/content/drive/MyDrive/MelodyResearch/final_csv/final_normalized/'+  'push_normalized_heavy_0.75.csv')

pull_normalized_25 = pd.read_csv('/content/drive/MyDrive/MelodyResearch/final_csv/final_normalized/'+  'pull_normalized_light_0.25.csv')
pull_normalized_50 = pd.read_csv('/content/drive/MyDrive/MelodyResearch/final_csv/final_normalized/'+  'pull_normalized_medium_0.5.csv')
pull_normalized_75 = pd.read_csv('/content/drive/MyDrive/MelodyResearch/final_csv/final_normalized/'+  'pull_normalized_heavy_0.75.csv')

folding_normalized_25 = pd.read_csv('/content/drive/MyDrive/MelodyResearch/final_csv/final_normalized/'+  'folding_normalized_light_0.25.csv')
folding_normalized_50 = pd.read_csv('/content/drive/MyDrive/MelodyResearch/final_csv/final_normalized/'+  'folding_normalized_medium_0.5.csv')
folding_normalized_75 = pd.read_csv('/content/drive/MyDrive/MelodyResearch/final_csv/final_normalized/'+  'folding_normalized_heavy_0.75.csv')

sponge_push_normalized_25 = pd.read_csv('/content/drive/MyDrive/MelodyResearch/final_csv/final_normalized/'+  'sponge_push_normalized_light_0.25.csv')
sponge_push_normalized_50 = pd.read_csv('/content/drive/MyDrive/MelodyResearch/final_csv/final_normalized/'+  'sponge_push_normalized_medium_0.5.csv')
sponge_push_normalized_75 = pd.read_csv('/content/drive/MyDrive/MelodyResearch/final_csv/final_normalized/'+  'sponge_push_normalized_heavy_0.75.csv')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
feature_columns = ['field.base.imu_acceleration_x',
                     'field.base.imu_acceleration_y',
                     'field.base.imu_acceleration_z',
                     'field.base.imu_angular_velocity_x',
                     'field.base.imu_angular_velocity_y',
                     'field.base.imu_angular_velocity_z',
                     'field.base.tool_pose_x',
                     'field.base.tool_pose_y',
                     'field.base.tool_pose_z',
                     'field.base.tool_pose_theta_x',
                     'field.base.tool_pose_theta_y',
                     'field.base.tool_pose_theta_z',
                     'field.base.tool_twist_linear_x',
                     'field.base.tool_twist_linear_y',
                     'field.base.tool_twist_linear_z',
                     'field.base.tool_twist_angular_x',
                     'field.base.tool_twist_angular_y',
                     'field.base.tool_twist_angular_z',
                     'field.base.commanded_tool_pose_x',
                     'field.base.commanded_tool_pose_y',
                     'field.base.commanded_tool_pose_z',
                     'field.base.commanded_tool_pose_theta_x',
                     'field.base.commanded_tool_pose_theta_y',
                     'field.base.commanded_tool_pose_theta_z',
                     'field.interconnect.imu_acceleration_x',
                     'field.interconnect.imu_acceleration_y',
                     'field.interconnect.imu_acceleration_z',
                     'field.interconnect.imu_angular_velocity_x',
                     'field.interconnect.imu_angular_velocity_y',
                     'field.interconnect.imu_angular_velocity_z',
                     'field.interconnect.oneof_tool_feedback.gripper_feedback0.motor0.position',
                     'field.interconnect.oneof_tool_feedback.gripper_feedback0.motor0.velocity',
                     'field.actuators0.position',
                     'field.actuators1.position',
                     'field.actuators2.position',
                     'field.actuators3.position',
                     'field.actuators4.position',
                     'field.actuators5.position',
                     'field.actuators0.velocity',
                     'field.actuators1.velocity',
                     'field.actuators2.velocity',
                     'field.actuators3.velocity',
                     'field.actuators4.velocity',
                     'field.actuators5.velocity',
                     'field.base.tool_external_wrench_force_x',
                     'field.base.tool_external_wrench_force_y',
                     'field.base.tool_external_wrench_force_z',
                     'field.base.tool_external_wrench_torque_x',
                     'field.base.tool_external_wrench_torque_y',
                     'field.base.tool_external_wrench_torque_z',
                     'field.actuators0.torque',
                     'field.actuators1.torque',
                     'field.actuators2.torque',
                     'field.actuators3.torque',
                     'field.actuators4.torque',
                     'field.actuators5.torque']

In [ ]:
good_datasets = [push_normalized, pull_normalized, folding_normalized, sponge_push_normalized]
dataset_names = ["push_normalized", "pull_normalized", "folding_normalized", "sponge_push_normalized"]



In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages

# Assuming you have the good datasets loaded into the 'good_datasets' list
# Assuming you have the feature_columns list defined
# Assuming you have the dataset_names list defined

# Set plot parameters
fig_width = 12  # Width of each subplot in inches
fig_height = 5  # Height of each subplot in inches (increased from 4)
num_plots_per_row = 4  # Number of plots to display in a row
pdf_filename = 'plotGridColor.pdf'  # Name of the output PDF file

# Define a list of colors for each dataset
colors = ['blue', 'green', 'red', 'purple']

# Create a PDF file to save the plots
pdf_pages = PdfPages(pdf_filename)

# Iterate over each feature
for feature in feature_columns:
    plt.figure(figsize=(fig_width, fig_height))

    # Iterate over each dataset and plot the current feature
    for dataset_idx, dataset in enumerate(good_datasets):
        df = pd.DataFrame(dataset, columns=feature_columns)
        plt.subplot(1, num_plots_per_row, dataset_idx + 1)

        # Get the color for the current dataset
        color = colors[dataset_idx % len(colors)]

        plt.plot(df[feature], color=color)
        plt.title(dataset_names[dataset_idx])
        plt.xlabel('Time')
        plt.ylabel('Value')

    # Add the feature name as a title for the row
    plt.suptitle(feature, y=0.95)  # Adjusted the y-coordinate for better visibility

    # Adjust spacing between subplots and title
    plt.tight_layout(rect=[0, 0, 1, 0.98])

    # Save the plot to the PDF file
    pdf_pages.savefig()
    plt.close()

# Close the PDF file
pdf_pages.close()

In [ ]:
# import numpy as np
# from sklearn.model_selection import train_test_split
# from sklearn.preprocessing import StandardScaler
# from tensorflow import keras
# from tensorflow.keras import layers
# import matplotlib.pyplot as plt


# # Concatenate all the good datasets into a single dataset
# good_datasets = [push_normalized, pull_normalized, folding_normalized, sponge_push_normalized]
# combined_good_data = np.concatenate(good_datasets)
# print(combined_good_data)

# # Concatenate all the bad datasets into a single dataset
# bad_datasets = [push_normalized_25, push_normalized_50, push_normalized_75,
#                 pull_normalized_25, pull_normalized_50, pull_normalized_75,
#                 folding_normalized_25, folding_normalized_50, folding_normalized_75,
#                 sponge_push_normalized_25, sponge_push_normalized_50, sponge_push_normalized_75]
# combined_bad_data = np.concatenate(bad_datasets)
# print(combined_bad_data)

[[0.2232349787933775 0.4404103544303659 0.6368912549596493 ... 0 0 0]
 [0.2181350308014931 0.461298769791135 0.6336184326490156 ... 0 0 0]
 [0.2181350308014931 0.461298769791135 0.6336184326490156 ... 0 0 0]
 ...
 [0.6904587234096746 0.2936691877085974 0.7302986548361687 ... 0 0 0]
 [0.6904587234096746 0.2936691877085974 0.7302986548361687 ... 0 0 0]
 [0.7451843574105441 0.3037245057396915 0.5552093627409246 ... 0 0 0]]
[[0.3513952636437825 0.2974872139379754 0.5970024112532059 ... 1 1 1]
 [0.092450463108473 0.6043706826525465 0.5195378338276457 ... 1 1 1]
 [0.1475033595946475 0.439818785603312 0.5002339522892114 ... 1 1 1]
 ...
 [0.0 0.0 0.6661823701495615 ... 1 1 1]
 [1.0 0.5267876150759389 1.0 ... 1 1 1]
 [0.5106544565881681 1.0 0.2195003574818064 ... 1 1 1]]


In [ ]:

# # Create the labels for the good data (0 indicates good)
# good_labels = np.zeros(combined_good_data.shape[0])

# # Create the labels for the bad data (1 indicates bad)
# bad_labels = np.ones(combined_bad_data.shape[0])

# # Combine the good and bad datasets
# combined_data = np.concatenate([combined_good_data, combined_bad_data])
# combined_labels = np.concatenate([good_labels, bad_labels])

# # Select the desired feature columns from your dataset
# selected_data = combined_data[:, [feature_columns.index(col) for col in feature_columns]]

# # Perform feature scaling if needed
# scaler = StandardScaler()
# scaled_data = scaler.fit_transform(selected_data)

# # Split the data into training and testing sets
# X_train, X_test, y_train, y_test = train_test_split(scaled_data, combined_labels, test_size=0.2, shuffle=False)

# # Reshape the data for LSTM input (assuming the shape of your data is [samples, timesteps, features])
# timesteps = 20  # Number of timesteps for each sequence
# n_features = selected_data.shape[1]  # Number of features in each timestep

# X_train = X_train.reshape(-1, timesteps, n_features)
# X_test = X_test.reshape(-1, timesteps, n_features)

# # Define the LSTM model
# model = keras.Sequential()
# model.add(layers.LSTM(64, input_shape=(timesteps, n_features)))
# model.add(layers.Dense(1, activation='sigmoid'))

# # Compile the model
# model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# # Train the model
# history = model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_test, y_test))

# # Evaluate the model on the testing set
# loss, accuracy = model.evaluate(X_test, y_test)
# print(f'Test Loss: {loss}, Test Accuracy: {accuracy}')

# # Plot the training and validation accuracy over epochs
# plt.plot(history.history['accuracy'])
# plt.plot(history.history['val_accuracy'])
# plt.title('Model Accuracy')
# plt.xlabel('Epoch')
# plt.ylabel('Accuracy')
# plt.legend(['Train', 'Validation'], loc='upper left')
# plt.show()

# # Plot the training and validation loss over epochs
# plt.plot(history.history['loss'])
# plt.plot(history.history['val_loss'])
# plt.title('Model Loss')
# plt.xlabel('Epoch')
# plt.ylabel('Loss')
# plt.legend(['Train', 'Validation'], loc='upper right')
# plt.show()



ValueError: ignored